
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 18 14:18:01 BRST 2016
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FRAC = 9;
  public static final int DIGIT1_9 = 8;
  public static final int MINUS = 5;
  public static final int LSQBRACKET = 3;
  public static final int DECIMAL_SEPARATOR = 6;
  public static final int NUMBER = 10;
  public static final int BOOLEAN = 11;
  public static final int NULL = 12;
  public static final int RSQBRACKET = 4;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMMA = 2;
  public static final int DIGITS = 7;
}

