
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 18 15:58:46 BRST 2016
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FRAC = 7;
  public static final int MINUS = 5;
  public static final int LSQBRACKET = 3;
  public static final int BOOLEAN = 10;
  public static final int NULL = 11;
  public static final int RSQBRACKET = 4;
  public static final int STRING = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMMA = 2;
  public static final int DIGITS = 6;
  public static final int EXP = 8;
}

