
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 18 23:43:10 BRST 2016
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 5;
  public static final int ARRAY_END = 4;
  public static final int NUMBER = 6;
  public static final int BOOLEAN = 8;
  public static final int OBJ_BEGIN = 10;
  public static final int NULL = 9;
  public static final int EOF = 0;
  public static final int STRING = 7;
  public static final int PAIR_SEPARATOR = 12;
  public static final int error = 1;
  public static final int ARRAY_BEGIN = 3;
  public static final int COMMA = 2;
  public static final int OBJ_END = 11;
}

